apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream node_apps {
        server app1-service:3000;
        server app2-service:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://node_apps;
        }
    }
