apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app1
  template:
    metadata:
      labels:
        app: node-app1
    spec:
      containers:
      - name: node-app1-container
        image: monabawi/node-app1:v1
        ports:
        - containerPort: 3000
